// Code generated by "stringer -type=RBDirection"; DO NOT EDIT.

package tree

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Left - -1]
	_ = x[Root-0]
	_ = x[Right-1]
}

const _RBDirection_name = "LeftRootRight"

var _RBDirection_index = [...]uint8{0, 4, 8, 13}

func (i RBDirection) String() string {
	i -= -1
	if i < 0 || i >= RBDirection(len(_RBDirection_index)-1) {
		return "RBDirection(" + strconv.FormatInt(int64(i+-1), 10) + ")"
	}
	return _RBDirection_name[_RBDirection_index[i]:_RBDirection_index[i+1]]
}
