// Code generated by command: go run asm.go -out fast_hash_match.s -stubs fast_hash_match_amd64.go. DO NOT EDIT.

//go:build amd64 && !nosimd

package kv

// Fast16WayHashMatch performs a 16-way linear probing of short hash (h2, metadata) list by SSE instructions
// short hash list must be an aligned pointer
func Fast16WayHashMatch(md *[16]int8, hash int8) uint16
