// Code generated by command: go run asm.go -out match_metadata.s -stubs match_metadata_amd64.go. DO NOT EDIT.

//go:build amd64

package kv

// MatchMetadata performs a 16-way linear probing of metadata by SSE instructions
// metadata must be an aligned pointer
func MatchMetadata(md *[16]int8, hash int8) uint16
